# Generated by Django 3.1.2 on 2020-10-22 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0002_auto_20201022_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 10, 22))),
                ('farm_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockedVegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('harvested_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetables.harvest')),
            ],
        ),
    ]
