# Generated by Django 3.1.2 on 2020-10-25 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0003_harvest_stockedvegetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 25)),
        ),
    ]
