# Generated by Django 3.1.2 on 2020-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20201029_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='photo',
            field=models.ImageField(default='/static/media/default.jpg', upload_to='images'),
        ),
    ]
