# Generated by Django 3.1.6 on 2021-03-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210308_0045'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseditem',
            name='purchased item can be either vegeetable or merchandise',
        ),
        migrations.AddConstraint(
            model_name='purchaseditem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('categories', 1), ('merchandise__isnull', True), ('stocked_vegetable__isnull', False)), models.Q(('categories', 2), ('merchandise__isnull', False), ('stocked_vegetable__isnull', True)), _connector='OR'), name='purchased item can be either vegetable or merchandise'),
        ),
    ]
