# Generated by Django 3.1.6 on 2021-05-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210519_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditem',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.transaction'),
        ),
    ]
