# Generated by Django 3.1.2 on 2020-11-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20201029_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='categories',
            field=models.CharField(choices=[('FRUIT', 'FRUIT'), ('VEGETABLE', 'VEGETABLE'), ('HERBS', 'HERBS'), ('SEASONAL', 'SEASONAL')], default='VEGETABLE', max_length=180),
        ),
    ]
