# Generated by Django 2.2.16 on 2020-11-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20201029_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='quantity',
            field=models.CharField(default='units', max_length=100),
        ),
    ]
