# Generated by Django 3.1.2 on 2020-11-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_vegetable_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.IntegerField()),
                ('food_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
