# Generated by Django 3.1.2 on 2020-11-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_vegetable_quantity'),
        ('apis', '0006_vegetable_categories'),
    ]

    operations = [
    ]
