# Generated by Django 3.1.2 on 2020-11-16 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.IntegerField()),
                ('food_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stocked_vegetable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.stockedvegetable')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('method_of_payment', models.CharField(max_length=100)),
                ('PurchasedItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.purchaseditem')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
