# Generated by Django 3.1.2 on 2020-11-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_merge_20201113_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='quantity',
        ),
    ]
