# Generated by Django 3.1.2 on 2020-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_remove_vegetable_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
