# Generated by Django 3.1.2 on 2020-11-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20201116_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditem',
            name='purchase_id',
        ),
    ]
