# Generated by Django 3.1.2 on 2020-11-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20201119_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='photo',
            field=models.ImageField(default='/static/default.jpg', upload_to='images'),
        ),
    ]
