# Generated by Django 3.1.2 on 2020-11-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_remove_purchaseditem_purchase_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='PurchasedItem',
            new_name='purchased_item',
        ),
    ]
