# Generated by Django 3.1.2 on 2020-11-19 15:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20201119_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'FRUIT'), (2, 'VEGETABLE'), (3, 'HERBS'), (4, 'SEASONAL')], max_length=7),
        ),
    ]
