# Generated by Django 3.1.2 on 2020-11-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20201119_1555'),
        ('apis', '0011_auto_20201116_0138'),
    ]

    operations = [
    ]
