# Generated by Django 3.1.2 on 2020-12-07 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0013_merge_20201130_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='purchased_item',
        ),
        migrations.AddField(
            model_name='purchaseditem',
            name='transaction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='apis.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
